export const administrationTaskCapabilities = {
  accessPage: "administration.access.read",
  assignPostAccess: "administration.post_access.assign",
  assignStaffRole: "administration.staff_roles.assign",
  createRole: "administration.roles.create",
  linkStaffAccount: "administration.staff.link",
  managePermissionOverrides: "administration.permission_overrides.manage",
  provisionStaff: "administration.staff.provision",
  updateRolePermissions: "administration.role_permissions.update",
} as const

export const commercialTaskCapabilities = {
  addBomLine: "pricing.assemblies.lines.add",
  addEnquiryItem: "pricing.enquiries.items.add",
  addPurchaseOrderLine: "pricing.purchase_orders.lines.add",
  applyEngineeringChangeDecision: "pricing.ecns.decision.apply",
  applyEnquiryImportReview: "pricing.enquiries.import_review.apply",
  approveProformaInvoice: "pricing.proforma_invoices.approve",
  cancelPurchaseOrder: "pricing.purchase_orders.cancel",
  completeBulkPriceRevision: "pricing.price_revisions.complete",
  completeEngineeringChangeCosting: "pricing.ecns.costing.complete",
  completeEngineeringChangeDesign: "pricing.ecns.design.complete",
  completeFollowup: "pricing.sales.followups.complete",
  completeSalesClarification: "pricing.sales.clarifications.complete",
  createBulkPriceRevision: "pricing.price_revisions.create",
  createCustomer: "pricing.customers.create",
  createEngineeringChangeNote: "pricing.ecns.create",
  createEnquiry: "pricing.enquiries.create",
  createPoQuoteRequest: "pricing.purchase_orders.quote_requests.create",
  createPurchaseOrder: "pricing.purchase_orders.create",
  decidePurchaseOrderLinePrice: "pricing.purchase_orders.prices.decide",
  deleteBulkPriceRevisionStage: "pricing.price_revisions.stages.delete",
  deleteEnquiry: "pricing.enquiries.delete",
  deleteMaster: "pricing.masters.delete",
  generateProformaInvoice: "pricing.proforma_invoices.generate",
  handOverEnquiry: "pricing.enquiries.handover",
  importEnquiryLines: "pricing.enquiries.lines.import",
  importEnquiryRegister: "pricing.enquiries.register.import",
  importMasters: "pricing.masters.import",
  importPurchaseOrder: "pricing.purchase_orders.import",
  markProformaInvoiceSent: "pricing.proforma_invoices.mark_sent",
  prepareCosting: "pricing.costing.prepare",
  recordPricingCorrection: "pricing.corrections.record",
  renameMaster: "pricing.masters.rename",
  requestDesignClarification: "pricing.design.clarifications.request",
  requestProductCostingClarification:
    "pricing.costing.design_clarifications.request",
  reverseDesignCostingHandoff: "pricing.corrections.design_handoff.reverse",
  reverseProductEntry: "pricing.corrections.product_entry.reverse",
  saveDesign: "pricing.design.save",
  saveQuote: "pricing.quotes.prepare",
  sendQuote: "pricing.quotes.send",
  sendQuoteBackToCosting: "pricing.quotes.return_to_costing",
  stageBulkPriceRevision: "pricing.price_revisions.stages.update",
  startDesignWork: "pricing.design.start",
  updateCustomer: "pricing.customers.update",
  updateDrawingHistory: "pricing.drawing_history.update",
  updateEnquiry: "pricing.enquiries.update",
  updateEnquiryItem: "pricing.enquiries.items.update",
  updateMaster: "pricing.masters.update",
  updateProductCosting: "pricing.costing.update",
  updateTechnicalReview: "pricing.technical_review.update",
  updateWebsiteProduct: "pricing.website_products.update",
  uploadPurchaseOrderFile: "pricing.purchase_orders.files.upload",
} as const

export const hrTaskCapabilities = {
  assignCandidate: "hr.candidates.assign",
  assignEmployee: "hr.employees.assign",
  bulkAssignEmployees: "hr.employees.bulk_assign",
  completeCandidateAppointment: "hr.candidates.appointments.complete",
  createCombinedRole: "hr.combined_roles.create",
  createJob: "hr.jobs.create",
  deleteCandidateEvent: "hr.candidates.events.delete",
  deletePost: "hr.approved_posts.delete",
  deleteRecruitmentMaster: "hr.masters.delete",
  logCandidateEvent: "hr.candidates.events.log",
  recordInterview: "hr.interviews.record",
  renameRecruitmentMaster: "hr.masters.rename",
  saveCandidate: "hr.candidates.save",
  savePost: "hr.approved_posts.create",
  saveRecruitmentMaster: "hr.masters.create",
  saveTemplate: "hr.job_templates.save",
  scheduleInterview: "hr.interviews.schedule",
  updateCandidateEvent: "hr.candidates.events.update",
  updateCombinedRole: "hr.combined_roles.update",
  updatePost: "hr.approved_posts.update",
  withdrawCandidateApplication: "hr.candidates.applications.withdraw",
} as const

export const taskCapabilityCatalog = {
  ...administrationTaskCapabilities,
  ...commercialTaskCapabilities,
  ...hrTaskCapabilities,
} as const

export type TaskCapability =
  (typeof taskCapabilityCatalog)[keyof typeof taskCapabilityCatalog]
